### ISSUE TITLE
SIC only Assembler

### ISSUE THREAD

**Issue by YousefSaber** [jurem/SicTools#9]
can you please introduce us an only SIC(besides the current SIC/XE Assembler) SIC Assembler that matches the specs , description and syntax of that in 
Introduction to Systems Programming
Book by Leland L. Beck
only pages 47 , 49 
here's the link for the reference 
https://drive.google.com/file/d/1lU-PKTmICybL2KxK1ExUHHMdwOTMKJtF/view?usp=sharing

**Comment by fraggerfox** [comment]
@YousefSaber , I am not sure if this would be of help, there is a pure C language implementation of only SIC that matches the specification, syntax and description as mentioned in Leland L. Beck's book here

https://github.com/fraggerfox/sicvm/tree/master/src/asm

There are some minor modifications like introduction of a `HLT` instruction to help stop the executing program, but for the vast majority it adheres to the original description.

It has been a while since I worked on the above project.

**Comment by YousefSaber** [comment]
@fraggerfox it worked without any mistakes thanks a lot
